apiVersion: v1
kind: Service
metadata:
  name: {{ include "text-extractor.fullname" . }}
  labels:
    {{- include "text-extractor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: shim
      protocol: TCP
      name: http
  selector:
    {{- include "text-extractor.selectorLabels" . | nindent 4 }}
