{{- if .Values.preJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "pre-job"
  labels:
    {{- include "base-otc.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "pre-job"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
      - name: "pre-job-container"
        image: "{{ .Values.preJob.image }}"
        env:
        {{- if .Values.preJob.env }}
        {{- range $key, $value := .Values.preJob.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        command:
        {{- if .Values.preJob.command }}
        {{- range .Values.preJob.command }}
        - {{ . | quote }}
        {{- end }}
        {{- end }}
{{- end }}
