{{- if not (empty .Values.container.secrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: "kubernetes.io/storageos"
data:
  {{- range $v := .Values.container.secrets }}
  {{ $v.name }} : {{ default "" $v.value | b64enc | quote }}
  {{- end }}
{{- end }}

