apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "text-extractor.fullname" . }}
  labels:
    {{- include "text-extractor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "text-extractor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "text-extractor.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "text-extractor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: tika
          securityContext:
            {{- toYaml .Values.tika.securityContext | nindent 12 }}
          image: "{{ .Values.tika.image.repository }}:{{ .Values.tika.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: tika
              containerPort: {{ .Values.tika.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.tika.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.tika.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.tika.resources | nindent 12 }}
          {{- with .Values.tika.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - name: shim
          securityContext:
            {{- toYaml .Values.shim.securityContext | nindent 12 }}
          image: "{{ .Values.shim.image.repository }}:{{ .Values.shim.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: shim
              containerPort: {{ .Values.shim.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.shim.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.shim.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.shim.resources | nindent 12 }}
          {{- with .Values.shim.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
